config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'dashboard', to: 'users#dashboard'

  devise_for :users, controllers: {
  sessions: 'users/sessions'
}
  resources :skills, only: [:new]
  resources :users, only: [:edit, :show, :index]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookings
  has_many :skills
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  #respond_to :js
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  #respond_to :js
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  skip_after_action :verify_policy_scoped, only: :edit

  def index
    @users = policy_scope(User).all
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def edit
    @user = current_user
    authorize @user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to dashboard_path
  end

  def dashboard
    @user = current_user
    @bookings = @user.bookings
    authorize @user
    # means we need to create a related Pundit policy
  end

  private

  def user_params
    require.params(:user).permit(:name, :babysitter, :address, :profile_description)
  end

end

app/views/users/dashboard.html.erb
<div class="dashboard-layout">
  <!-- USER BOX START -->
  <div class="user">
    <% if current_user.babysitter %>
      <div class="user-infos">
        <div class="avatar">
          <img src="http://via.placeholder.com/80x80" alt="Avatar">
          <div class="switch">
            <input id="cmn-toggle-1" class="cmn-toggle cmn-toggle-round" type="checkbox">
            <label for="cmn-toggle-1"></label>
          </div>
        </div>
        <div class="user-infos-right">
          <div class="user-name">
            <h2><%= current_user.name %></h2>
          </div>
          <div class="address">
            <p><%= current_user.address %></p>
          </div>
        </div>
      </div>
      <div class="user-description">
        <p>"<%= current_user.profile_description %>"</p>
      </div>
      <div align="right">
        <a href="#" class="btn btn-primary">EDIT</a>
      </div>
    <% else %>
      <div class="user-infos">
        <div class="avatar">
          <img src="http://via.placeholder.com/80x80" alt="Avatar">
        </div>
        <div class="user-infos-right">
          <div class="user-name">
            <h2><%= current_user.name %></h2>
          </div>
          <div class="address">
            <p><%= current_user.address %></p>
          </div>
        </div>
      </div>
      <div align="right">
        <a href="#" class="btn btn-primary">EDIT</a>
      </div>
    <% end %>
  </div>
  <!-- USER BOX FINISH -->

  <!-- SKILLS BOX START: Babysitter ONLY -->
  <% if current_user.babysitter %>
    <div class="skills">
      <div class="skills-grid">
        <% current_user.skills.each do |skill| %>
        <div class="skill">
          <p><%= skill.content %></p>
        </div>
        <% end %>
      </div>
      <div align="right">
        <%= link_to "EDIT", new_skill_path(current_user), class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
  <!-- SKILLS BOX FINISH -->

  <!-- BOOKINGS BOX START -->
  <div class="bookings">
    <h1>Manage Bookings</h1>
    <div class="booking-cards">
      <div class="card">
        <div class="card-left avatar">
          <img src="http://via.placeholder.com/50x50" alt="Avatar">
          <h2>Parent Name</h2>
        </div>
        <div class="card-middle">
          <p class="message">"Hello, my name is Jane Doe and I have two children, age five and three. My son Will is lactose intolerent so I would benefit from your cooking. I need someone for the next couple of weeks, Saturday and Sunday."</p>
        </div>
        <div class="card-right">
          <a href="#" class="btn btn-primary">Yes</a>
          <a href="#" class="btn btn-primary">No</a>
        </div>
      </div>
    </div>
  </div>
  <!-- BOOKINGS BOX FINISH -->
</div>

app/views/users/index.html.erb
<h1>hello</h1>